use_frameworks!

target 'ZXPhotoPicker_Example' do
    pod 'ZXPhotoPicker', :path => '../'

    target 'ZXPhotoPicker_Tests' do
        inherit! :search_paths

        pod 'Quick', '~> 1.2.0'
        pod 'Nimble', '~> 7.0.2'
        pod 'FBSnapshotTestCase' , '~> 2.1.4'
        pod 'Nimble-Snapshots' , '~> 6.3.0'
    end
end
